version: '3'
services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3300:3300' 
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  server-side:
    container_name: server-side
    build: server-side/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server-side:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0
  client-side:
    container_name: client-side
    build: client-side/
    command: yarn dev
    volumes:
      - ./client-side:/myapp
    ports:
      - 8080:3000
    depends_on:
      - server-side
volumes:
  mysql-data:
    driver: local